### ISSUE TITLE
docker registry behind https-portal

### ISSUE THREAD

**Issue by scher200** [SteveLTN/https-portal#13] opened 2016-01-28 22:11 UTC
I am trying to setup a docker registry behind the https portal,
but i can not get it to work:

this was the output:

https-portal_1 | Starting docker-gen ...
https-portal_1 | Starting crond ...
https-portal_1 | 2016/01/28 20:25:23 Generated '/var/run/domains' from 6 containers
https-portal_1 | 2016/01/28 20:25:23 Running 'reconfig'
https-portal_1 | 12.12.12.122 - - [28/Jan/2016:20:25:25 +0000] "GET /.well-known/acme-challenge/0L8oxvvmfzfNB42zQmi2kgxgipY41Kmu99JgxJZFQ0M HTTP/1.1" 200 87 "-" "Python-urllib/2.7" "-"
https-portal_1 | 66.133.109.36 - - [28/Jan/2016:20:25:27 +0000] "GET /.well-known/acme-challenge/0L8oxvvmfzfNB42zQmi2kgxgipY41Kmu99JgxJZFQ0M HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: 2016/01/28 20:25:23 [notice] 166#166: signal process started
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Generating RSA private key, 2048 bit long modulus
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: ......+++
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: ..+++
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: unable to write 'random state'
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: e is 65537 (0x10001)
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Signing certificates from https://acme-staging.api.letsencrypt.org ...
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Parsing account key...
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Parsing CSR...
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Registering account...
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Registered!
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Verifying registry.testtest.nl...
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: registry.testtest.nl verified!
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Signing certificate...
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Certificate signed!
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: 2016/01/28 20:25:33 [notice] 185#185: signal process started
https-portal_1 | 2016/01/28 20:25:33 [reconfig]: Signed key for registry.testtest.nl
https-portal_1 | 2016/01/28 20:25:33 Watching docker events

from this docker-compose file:
https-portal:
  restart: always
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./data/ssl_certs:/var/lib/https-portal
    - ./data/http_config:/var/lib/nginx-conf:ro
    - ./data/http_pass:/var/etc/passwords:ro
  environment:
    PRODUCTION: 'true'
  container_name: https_portal

I tried Force renew

**Comment by SteveLTN** [comment] 2016-01-28 22:48
Hi,

`unable to write 'random state'` means OpenSSL cannot write into `/root/.rnd`, please make sure you didn't make it unwritable.

In your pasted output, you are connecting to the staging Let's Encrypt server `https://acme-staging.api.letsencrypt.org`, however in your compose file you are using production mode.
I would guess the compose file you pasted is not actually being used.

**Comment by scher200** [comment] 2016-01-29 11:52
OK, I did not toch that file at all, but after a:

docker exec httpsportal chmod go+rw /root/.rnd
docker commit httpsportal httpsportal

it was fixed and the certificate was excepted in my browser directly after
recreating my docker-compose.
This time with the newly created image: httpsportal

Thank you

2016-01-28 23:48 GMT+01:00 Weiyan Shao <notifications@github.com>:

> Hi,
>
> unable to write 'random state' means OpenSSL cannot write into /root/.rnd,
> please make sure you didn't make it unwritable.
>
> In your pasted output, you are connecting to the staging Let's Encrypt
> server https://acme-staging.api.letsencrypt.org, however in your compose
> file you are using production mode.
> I would guess the compose file you pasted is not actually being used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveLTN/https-portal/issues/13#issuecomment-176465373>
> .
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by SteveLTN** [comment] 2016-01-29 12:48
It's a bit weird, because the image should by default come with `/root/.rnd` writable and I couldn't reproduce the problem.

The only way I can make it unwritable is to mount some host folder into `/root` and use `ro`.

**Comment by scher200** [comment] 2016-01-29 13:52
Uhm strange, after booting and launching it again en relaunching my registry:
root@bliksembelang:/mnt/extern/agents/registry# docker exec -it https_portal bash
root@d8da4d22efd5:~# ls
root@d8da4d22efd5:~# ls -la
total 24
drwx------  2 root root 4096 Jan 29 11:46 .
drwxr-xr-x 64 root root 4096 Jan 29 12:17 ..
-rw-------  1 root root   75 Jan 29 11:44 .bash_history
-rw-r--r--  1 root root  570 Jan 31  2010 .bashrc
-rw-r--r--  1 root root  140 Nov 19  2007 .profile
-rw-------  1 root root 1024 Jan 29 11:46 .rnd

it was like that again. Is that OK, does it change permission on launching?
I did no mounting of /root/ at all.
Later after the recreating of my registry container it just lost its signedness.
Even though i did mount:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./data/ssl_certs:/var/lib/https-portal
    - ./data/http_config:/var/lib/nginx-conf:ro
    - ./data/http_pass:/var/etc/passwords:ro

**Comment by SteveLTN** [comment] 2016-01-29 13:59
You've been trying for many times. Due to the rate limit of Let's Encrypt, I suggest you turn off production mode while trying.

For me, every time when OpenSSL finishes his work, `.rnd` will be deleted so next time it wouldn't cause any problems. It's really strange that it keep living there. Maybe you can try to run it without mounting all volumes except `docker.sock` first?

To keep the certificates, you don't have to mount a volume on manually. It will automatically mount an anonymous volume and keep the certificates.

**Comment by scher200** [comment] 2016-01-29 16:16
Hi Weiyan,

I tried it all and after all i run a jwilder/nginx-proxy with the generated
and signed certs from
/var/lib/https-portal/<domain-name>/* (had to rename chained.pem to
<domain-name>.crt and domain.key to <domain-name>.key)
than pass them into nginx certs directory and launch the project like this:
http://blog.mechanical.ninja/post/docker/deploy-simple-registry/

And it works it is amazing.

I still like your https-portal more but it just does not work in
combination with the tutorial from the link

Thank you for helping me





2016-01-29 14:59 GMT+01:00 Weiyan Shao <notifications@github.com>:

> You've been trying for many times. Due to the rate limit of Let's Encrypt,
> I suggest you turn off production mode while trying.
>
> For me, every time when OpenSSL finishes his work, .rnd will be deleted
> so next time it wouldn't cause any problems. It's really strange that it
> keep living there. Maybe you can try to run it without mounting all volumes
> except docker.sock first?
>
> To keep the certificates, you don't have to mount a volume on manually. It
> will automatically mount an anonymous volume and keep the certificates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveLTN/https-portal/issues/13#issuecomment-176766011>
> .
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by SteveLTN** [comment] 2016-01-29 16:31
Great, jwilder's nginx-proxy is awsome, I've been using it until I decided to make Let's Encrypt automated in a container. Just make sure to renew the certs in 3 months.

I still don't get why OpenSSL will fail to write into `/root/.rnd` though... It's a mystery now. :-)

**Comment by SteveLTN** [comment] 2016-01-29 16:43
BTW have you tried `docker-compose up --force-recreate` ?

**Comment by SteveLTN** [comment] 2016-01-29 16:55
I think I know where the issue is.

When the HTTPS-PORTAL starts, it tries to create dhparam and account keys. However, the auto-discovery feature is triggered and OpenSSL tries to create another certs. Both OpenSSL processes want to write into `/root/.rnd` which causes a conflict. 

I'm working on a fix for this. Sorry for inconvenience.

**Comment by SteveLTN** [comment] 2016-01-29 18:09
No, unfortunately it's not because of that ...

**Closed by SteveLTN** 2016-01-29 18:09 UTC

**Comment by scher200** [comment] 2016-01-29 22:19
ah, to bad i could not find out why this happens to me. I run docker 1.8.1 on this server.
Maybe that is what is causing it. 
Also tried the docker-compose up --force-recreate
but it does not make any new directories in /var/lib/https-portal
except for the *-stagging ones

after launching another conatiner with another domain i got:
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: 2016/01/29 22:11:40 [notice] 205#205: signal process started
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Generating RSA private key, 2048 bit long modulus
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: .........+++
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: ...........................+++
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: unable to write 'random state'
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: e is 65537 (0x10001)
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Signing certificates from https://acme-staging.api.letsencrypt.org ...
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Parsing account key...
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Parsing CSR...
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Registering account...
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Already registered!
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Verifying server.bliksembelang.nl...
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Traceback (most recent call last):
https-portal_1 | 2016/01/29 22:11:42 [reconfig]:   File "/bin/acme_tiny", line 198, in <module>
https-portal_1 | 2016/01/29 22:11:42 [reconfig]:     main(sys.argv[1:])
https-portal_1 | 2016/01/29 22:11:42 [reconfig]:   File "/bin/acme_tiny", line 194, in main
https-portal_1 | 2016/01/29 22:11:42 [reconfig]:     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1 | 2016/01/29 22:11:42 [reconfig]:   File "/bin/acme_tiny", line 123, in get_crt
https-portal_1 | 2016/01/29 22:11:42 [reconfig]:     wellknown_path, wellknown_url))
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: ValueError: Wrote file to /var/www/challenges/BWxAOC-0KH5BcBmhGo3-S2WiGM6S8cxtvqn4D5oCvGE, but couldn't download http://server.bliksembelang.nl/.well-known/acme-challenge/BWxAOC-0KH5BcBmhGo3-S2WiGM6S8cxtvqn4D5oCvGE
https-portal_1 | 2016/01/29 22:11:42 [reconfig]: Failed to obtain certs for someother.otherbaseurlto.nl 

that output. Maybe it's good to know this was the output of: docker exec -it https_portal ls -lah
total 24K
drwx------  2 root root 4.0K Jan 29 11:43 .
drwxr-xr-x 62 root root 4.0K Jan 29 22:11 ..
-rw-------  1 root root   75 Jan 29 11:44 .bash_history
-rw-r--r--  1 root root  570 Jan 31  2010 .bashrc
-rw-r--r--  1 root root  140 Nov 19  2007 .profile
-rw-rw-rw-  1 root root 1.0K Jan 28 20:25 .rnd
 
seems .rnd was indeed not the problem of the unable to write 'random state'
